I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 281, in script
    robby "woah what did that bottle do?"
  File "game/script.rpy", line 281, in script
    robby "woah what did that bottle do?"
Exception: Sayer 'robby' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/ethanearle/Downloads/Renpy/renpy/bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "/Users/ethanearle/Downloads/Renpy/renpy/main.py", line 670, in main
    run(restart)
  File "/Users/ethanearle/Downloads/Renpy/renpy/main.py", line 144, in run
    renpy.execution.run_context(True)
  File "/Users/ethanearle/Downloads/Renpy/renpy/execution.py", line 955, in run_context
    context.run()
  File "game/script.rpy", line 281, in script
    robby "woah what did that bottle do?"
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 281, in script
    robby "woah what did that bottle do?"
  File "/Users/ethanearle/Downloads/Renpy/renpy/ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/ethanearle/Downloads/Renpy/renpy/ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'robby' is not defined.

macOS-13.4.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
CaveGame 1.0
Wed Nov 29 23:53:32 2023
